apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-tomsign
  namespace: trd-backend
  labels:
    app: trd-sign
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trd-sign
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       app: trd-sign
    spec:
      containers:
      - image: 
        name: sign
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi
            cpu: 400m
          limits:
            memory: 512Mi
            cpu: 400m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: pv-trd-sign
          mountPath: /trd/sign
      volumes:
      - name: pvc-trd-sign
        persistentVolumeClaim:
          claimName: pvc-trd-sign
      nodeSelector:
        app: trd-login

---

apiVersion: v1
kind: Service
metadata:
  name: trd-sign-svc
spec:
  selector:
    app: trd-sign
  type: ClusterIP
  clusterIP: 10.100.100.102
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
