apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-tomindex
  namespace: trd-backend
  labels:
    app: trd-index
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trd-index
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       app: trd-index
    spec:
      containers:
      - image: 
        name: index
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 400m
          limits:
            memory: 512Mi
            cpu: 400m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: pv-trd-index
          mountPath: /trd/index
      volumes:
      - name: pv-trd-index
        persistentVolumeClaim:
          claimName: pvc-trd-index
      nodeSelector:
        app: trd-index

---

apiVersion: v1
kind: Service
metadata:
  name: trd-index-svc
spec:
  selector:
    app: trd-index
  type: ClusterIP
  clusterIP: 10.100.100.101
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
