apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-login
  namespace: trd-frontend
  labels:
    app: trd-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trd-login
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       app: trd-login
    spec:
      containers:
      - image: 
        name: login
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 256Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: pv-trd-login
          mountPath: /trd/login
      volumes:
      - name: pvc-trd-login
        persistentVolumeClaim:
          claimName: pvc-trd-login
      nodeSelector:
        app: trd-login

---

apiVersion: v1
kind: Service
metadata:
  name: trd-login-svc
spec:
  selector:
    app: trd-login
  type: NodePort
  clusterIP: 10.100.100.103
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 33000
