apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvweb
spec:
# 8Gi로 용량을 설정하였습니다. 
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  # 여러 노드에서 볼륨을 읽고 쓸 수 있도록 지원
  # k8s-worker1, k8s-worker2의 두 워커 노드 중 
  #하나가 비정상 종료되더라도 하나의 워커 노드가 대신 수행 가능하게 설정했습니다.
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: web-sc # 영구 볼륨과 영구 볼륨 클레임 간 연결을 정의합니다.
  hostPath:
    path: /data/web
    type: DirectoryOrCreate

---

# PVC (PV 부분에서 정의했던 것과 똑같이 정의해야 합니다.)
# 그렇지 않을 경우 pv가 bound되지 않습니다.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcweb
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: web-sc
