apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem

  # 여러 노드가 읽고 쓸 수 있도록 accessModes을 설정하여
  # 다른 노드에도 마운트될 수 있도록 설정했습니다.
  # 이를 통해 한 노드가 종료되더라도 다른 노드가 정상 동작하게끔 구현하였습니다.
  
  accessModes:
    - ReadWriteMany

  # Tomcat의 pv에는 web service에 사용되는 file들이 대거 저장되어 있습니다.
  # Tomcat의 특정 파드가 비정상적으로 종료되더라도 클러스터에 pv의 데이터를 보존하기 위해
  # Retain 정책을 부여하였습니다.
  
  persistentVolumeReclaimPolicy: Retain
  
  storageClassName: was-sc
  hostPath:
    path: /data/was
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcwas
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: was-sc
