apiVersion: apps/v1
kind: Deployment
metadata:
  name: trd-prd-sign
  namespace: trd-frontend
  labels:
    app: trd-sign
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trd-sign
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
       app: trd-sign
    spec:
      containers:
      - image: 
        name: sign
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 256Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: pv-trd-sign
          mountPath: /trd/sign
      volumes:
      - name: pvc-trd-sign
        persistentVolumeClaim:
          claimName: pvc-trd-sign
      nodeSelector:
        app: trd-sign

---

apiVersion: v1
kind: Service
metadata:
  name: trd-sign-svc
spec:
  selector:
    app: trd-sign
  type: NodePort
  clusterIP: 10.100.100.102
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
