apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-main
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: efs-sc
  nfs:
    path: /
    server: 
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-main
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
