apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tom
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: efs-sc
  nfs:
    path: /trd-tomcat
    server: 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tom
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc