apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: trd-prd-cluster
  region:  ap-northeast-2
vpc:
  subnets:
    private:
      # ng-worker1-Node 그룹에서 ap-northeast-2a 가용 영역 담당
      ap-northeast-2a: { id: subnet-0a65ca3343682ed66 }

      # ng-worker2-Node 그룹에서 ap-northeast-2c 가용 영역 담당
      ap-northeast-2c: { id: subnet-020f8f4e1a87ad05a }

managedNodeGroups:
  - name: TRD-PRD-eks-cluster-ng-worker1-Node
    labels: { role: workers }
    instanceType: t3.medium

    # 원하는 인스턴스 수
    desiredCapacity: 1

    privateNetworking: true
    subnets:
      - subnet-0a65ca3343682ed66
      
  - name: TRD-PRD-eks-cluster-ng-worker2-Node
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - subnet-020f8f4e1a87ad05a
    iam:
      withAddonPolicies:
        imageBuilder: true