apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trd-prd-index-hpa
  namespace: trd-frontend
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trd-prd-index
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trd-prd-sign-hpa
  namespace: trd-frontend
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trd-prd-sign
  targetCPUUtilizationPercentage: 50
  ---
  apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trd-prd-login-hpa
  namespace: trd-frontend
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trd-prd-login
  targetCPUUtilizationPercentage: 50
  ---
  apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trd-prd-doc-hpa
  namespace: trd-frontend
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trd-prd-doc
  targetCPUUtilizationPercentage: 50
  ---apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trd-prd-docrg-hpa
  namespace: trd-frontend
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trd-prd-docrg
  targetCPUUtilizationPercentage: 50